### ISSUE TITLE
sortowanie wypożyczeń po użytkowniku

### ISSUE THREAD

**Issue by marcin3006** [szarafinski/JDBCProjekt#17]
Dodam możliwość sortowania wypożyczen np po imieniu, nazwisku, autorze, tytule

**Comment by szarafinski** [comment]
to zapewnia model TABLEVIEW automatycznie, nie trzeba nic dodawać/modyfikować by to zadziałało. 
Warto ewentualnie zmienić domyślną szerokość danej kolumny lub ich kolejność

**Comment by marcin3006** [comment]
Wiem, sorki dopiero zauwazylem to po dodaniu ISSU, faktycznie jest sortowanie a nie widzialem tego bo dopiero sortuje jak kliniesze na tabele a na pierwszy rzut oka nie widac ze jest taka mozliwosc.

**Comment by szarafinski** [comment]
zamykam
