### ISSUE TITLE
Poprawie wyświetlanie komunikatów 

### ISSUE THREAD

**Issue by marcin3006** [szarafinski/JDBCProjekt#19]
Poprawie wyswietlanie komunikatów np. po dodaniu uzytkownika

**Comment by szarafinski** [comment]
Marcin, to zostało już poprawione w issue #9 i zamknięte

**Comment by marcin3006** [comment]
Chodziło mi by dodać przycisk np OK by z okna komunikatow nie wychodzic przez X. Ja ściągnąłem nowa wersje programu z gita i nie było tam takiej mozliwości.

**Comment by szarafinski** [comment]
jest to już mi przypisane w #8 , nie ma potrzeby dublowania problemów
