### ISSUE TITLE
Wyświetlanie statusu wypożyczenia

### ISSUE THREAD

**Issue by marcin3006** [szarafinski/JDBCProjekt#21]
Zmodywikuję bazę danych by była możliwość na stałe wpisania jakiejś ilości ksiazek która biblioteka posiada. Użytkownik wypożyczając ksiażke będzie powodował zmienijszenie jej ilości w bibliotece. Odwrotnie bedzie przy możliwości zwrotu czyli stan bedzie się zwiększał. Następnie w ostatniej zakładce będzie wyświetlony stan wypożyczenie.

**Comment by szarafinski** [comment]
będzie trzeba zmienić tutaj nie tylko plik bazy danych, ale także samą funkcjonalność programu w tym funkcji zapisujących i odczytujących. 
W zakładce z informacją o książkach będzie trzeba dodać nową kolumnę informującą ile jest książek na stanie w bibliotece.
